CREATE USER IF NOT EXISTS 'coniiti_app'@'%' IDENTIFIED BY 'coniiti_app_2026!';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON `CONIITI_AUTH`.*
TO 'coniiti_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON `CONIITI_CONFERENCIAS`.*
TO 'coniiti_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON `CONIITI_CONFERENCISTAS`.*
TO 'coniiti_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON `CONIITI_FECHAS`.*
TO 'coniiti_app'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
ON `CONIITI_CONTACTO`.*
TO 'coniiti_app'@'%';

FLUSH PRIVILEGES;
